### ISSUE TITLE
Request for support on a few features

### ISSUE THREAD

**Issue by jasperchua99** [cx690/table2canvas#1]
Hi, im wondering if you can add a few features that could make this repo more usable for me to handle some of my projects

Currently i am working on replicating one of my tables i generate with another repo canvas-tables but theres issues i am not able to deal with unless the dev adds a few more functions. 
![image](https://user-images.githubusercontent.com/30612883/156154655-ec5019a6-5ea8-4ca3-9346-16fa9748b6df.png)

Likewise for here i am hoping if you are able to further develop this repo to make it better suit for some of my applications.

These are my features ill like to ask if you could implement
- Allow Table color change on the frame 
- Allow automatic fitting of table to the canvas size, and if needed block out some of the words like in the image

Hope to hear from you soon

**Comment by cx690** [comment]
Table color change,you can use `bgColor` to change all image's background,you can use `style.headerBgColor` change thead's background.
canvas's size:if your table's width fiexd,such as 800px,your column's count is 8,you can set `TableStyle.columnWidth = 100`,in this way,the table will be about 800px.
The last,"block out some of the words".this library is for node server side to generate image,The text overflow hidden seem like meaningless.if you think it is necessary,I can add the features.

**Comment by cx690** [comment]
v1.3.0: add some features.
```js
const columns: IColumn[] = [
    { title: 'Type', dataIndex: 'type', textAlign: 'center', textOverflow: 'ellipsis' },//use textOverflow block out some of the words
    { title: 'Efficiency', dataIndex: 'efficiency', textAlign: 'center', textOverflow: 'ellipsis', width: 100 },
    { title: 'Max', dataIndex: 'max', textAlign: 'center', width: 60 },
]

const dataSource: any[] = [
    { type: 'CL Guns (aaaaaaaaaaaaaaaaa', efficiency: '90>120>130>150', max: 2, },
    { type: 'tarpedoes', efficiency: '60>120>130>150', max: 1, },
    { type: 'anti-air Guns', efficiency: '70>80>90', max: 1, },
]

const table = new Table2canvas({
    canvas: new Canvas(2, 2),
    columns: columns,
    dataSource: dataSource,
    bgColor: '#aaf',//canvas background
    style: {
        background: 'rgba(0,0,0,0.7)',//table background
        color: '#fff'
    }
})
```
![a](https://user-images.githubusercontent.com/37604988/160798853-066440fe-3f9f-4891-813d-7302671b5edc.png)

Good luck!
