### ISSUE TITLE
multiline support?

### ISSUE THREAD

**Issue by Keller18306** [cx690/table2canvas#2]
![test-Понедельник](https://user-images.githubusercontent.com/23178771/220054622-e26f5eb6-dc74-4c20-aa8e-132426849bd0.png)

**Comment by cx690** [comment]
multiline is supported at version 2.0.1,there is a lot of changes.
now, use '\n' can set a new line. if text overflow, it will also fill in new line.
![image](https://user-images.githubusercontent.com/37604988/236753291-79cc1961-ac61-407a-b60f-7e244fddc95d.png)

**Comment by cx690** [comment]
multiline is supported at version 2.0.1+
