### ISSUE TITLE
有辦法支持自訂字體嗎

### ISSUE THREAD

**Issue by kiki-kanri** [cx690/table2canvas#4]
我在linux上產生表格，請問有辦法使用載入檔案的方式載入字體嗎，還是系統上一定要安裝字體檔

**Comment by cx690** [comment]
除了系統上安裝字體外，可以使用以下方法臨時註冊一種字體
```js
import { registerFont } from 'canvas';
registerFont('comicsans.ttf', { family: 'Comic Sans' });
```
然後設置配置項中的fontFamily屬性為註冊的family，就可以使用臨時方式載入字體

**Comment by kiki-kanri** [comment]
好的 非常感謝!，另外想問一下可以設置cell文字禁止換行嗎，有時候就算使用textOverflow ellipsis還是會到第二行去

**Comment by cx690** [comment]
這是一個bug，內部字符串截取問題

**Comment by cx690** [comment]
已在2.0.4修復

**Comment by kiki-kanri** [comment]
好的 非常感謝您
